/**
 * @see <a href="https://projecteuler.net/problem=2">Even Fibonacci numbers</a>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public final class P0002 {

    public static void main(final String[] args) {
        long previousNumber = 0;
        long currentNumber = 1;
        long fibonacciNumber = 0;
        long sumOfEvenFibonacci = 0;
        for(; fibonacciNumber < 4000000; ) {
            fibonacciNumber = currentNumber + previousNumber;
            previousNumber = currentNumber;
            currentNumber = fibonacciNumber;
            if(fibonacciNumber % 2 == 0) {
                sumOfEvenFibonacci += fibonacciNumber;
            }
        }
        System.out.println("Answer for P0002: " + sumOfEvenFibonacci);
    }
}